
import { ProvisioningPlan } from "../../../provisioning/catalogs";

export const examplePlan: ProvisioningPlan = {
    schemaVersion: "1.0",
    version: "1.0.0",
    parameters: [
        { key: "TenantUrl", value: "https://apveelabs.sharepoint.com" },
        { key: "TeamSiteAlias", value: "project-alpha-team-2" },
        { key: "TeamSiteDisplayName", value: "Project Alpha Team" },
        { key: "TeamSiteDescription", value: "Microsoft 365 Group-backed team site for Project Alpha collaboration" },
        { key: "CommSiteName", value: "engineering-portal-test-2" },
        { key: "CommSiteTitle", value: "Engineering Portal" },
        { key: "CommSiteDescription", value: "Communication site for engineering department announcements and resources" },
        { key: "RequestCategoriesListName", value: "requestCategories" },
        { key: "EngineeringRequestsListName", value: "engineeringRequests" },
        { key: "EngineeringDocumentsListName", value: "engineeringDocuments" },
    ],
    actions: [
        {
            verb: "createSPSite",
            siteType: "TeamSite",
            displayName: "{parameter:TeamSiteDisplayName}",
            alias: "{parameter:TeamSiteAlias}",
            url: "{parameter:TenantUrl}/sites/{parameter:TeamSiteAlias}",
            description: "{parameter:TeamSiteDescription}",
            isPublic: false,
            lcid: 1033,
        },
        {
            verb: "createSPSite",
            siteType: "CommunicationSite",
            title: "{parameter:CommSiteTitle}",
            url: "{parameter:TenantUrl}/sites/{parameter:CommSiteName}",
            description: "{parameter:CommSiteDescription}",
            lcid: 1033,
            webTemplate: "SITEPAGEPUBLISHING#0",
        },
        {
            verb: "modifySPSite",
            siteUrl: "{parameter:TenantUrl}/sites/{parameter:CommSiteName}",
            title: "{parameter:CommSiteTitle} (Updated)",
            description: "Updated: {parameter:CommSiteDescription}",
            subactions: [
                {
                    verb: "createSPSiteColumn",
                    fieldType: "Text",
                    fieldName: "TemporarySiteField",
                    displayName: "Temporary Site Field",
                    maxLength: 80,
                    required: false,
                },
                {
                    verb: "modifySPField",
                    fieldType: "Text",
                    fieldName: "TemporarySiteField",
                    displayName: "Temporary Site Field",
                    maxLength: 120,
                },
                {
                    verb: "createSPSiteColumn",
                    fieldType: "Currency",
                    fieldName: "ProjectBudget",
                    displayName: "Project Budget",
                    minimumValue: 0,
                    maximumValue: 1000000,
                    currencyLocaleId: 1033,
                    defaultValue: 0,
                    required: false,
                },
                {
                    verb: "modifySPField",
                    fieldType: "Currency",
                    fieldName: "ProjectBudget",
                    maximumValue: 2500000,
                    defaultValue: 1000,
                },
                {
                    verb: "createSPSiteColumn",
                    fieldType: "DateTime",
                    fieldName: "ProjectStartDate",
                    displayName: "Project Start Date",
                    displayFormat: "DateOnly",
                    calendarType: "Gregorian",
                    friendlyDisplayFormat: "Disabled",
                    required: false,
                },
                {
                    verb: "modifySPField",
                    fieldType: "DateTime",
                    fieldName: "ProjectStartDate",
                    friendlyDisplayFormat: "Relative",
                },
                {
                    verb: "createSPSiteColumn",
                    fieldType: "Boolean",
                    fieldName: "ProjectIsActive",
                    displayName: "Project Is Active",
                    defaultValue: true,
                    required: false,
                },
                {
                    verb: "modifySPField",
                    fieldType: "Boolean",
                    fieldName: "ProjectIsActive",
                    defaultValue: false,
                },
                {
                    verb: "createSPSiteColumn",
                    fieldType: "Choice",
                    fieldName: "ProjectPriority",
                    displayName: "Project Priority",
                    choices: ["Low", "Medium", "High"],
                    editFormat: "Dropdown",
                    fillInChoice: false,
                    defaultChoice: "Medium",
                    required: false,
                },
                {
                    verb: "modifySPField",
                    fieldType: "Choice",
                    fieldName: "ProjectPriority",
                    choices: ["Low", "Medium", "High", "Critical"],
                    defaultChoice: "High",
                },
                {
                    verb: "createSPSiteColumn",
                    fieldType: "MultiChoice",
                    fieldName: "ProjectTags",
                    displayName: "Project Tags",
                    choices: ["Frontend", "Backend", "DevOps", "Security"],
                    fillInChoice: true,
                    defaultValue: ["Backend", "DevOps"],
                    required: false,
                },
                {
                    verb: "modifySPField",
                    fieldType: "MultiChoice",
                    fieldName: "ProjectTags",
                    defaultValue: ["Backend"],
                },
                {
                    verb: "createSPSiteColumn",
                    fieldType: "Url",
                    fieldName: "ProjectWebsite",
                    displayName: "Project Website",
                    displayFormat: "Hyperlink",
                    defaultValue: "https://example.com",
                    required: false,
                },
                {
                    verb: "modifySPField",
                    fieldType: "Url",
                    fieldName: "ProjectWebsite",
                    displayFormat: "Image",
                },
                {
                    verb: "createSPList",
                    listName: "{parameter:RequestCategoriesListName}",
                    title: "Request Categories",
                    desc: "Lookup source list for request categories",
                    template: 100,
                    enableContentTypes: false,
                    hidden: false,
                    onQuickLaunch: true,
                    enableAttachments: true,
                    enableFolderCreation: false,
                    enableVersioning: true,
                    forceCheckout: false,
                    majorVersionLimit: 50,
                    readSecurity: 1,
                    writeSecurity: 1,
                    noCrawl: false,
                    enableModeration: false,
                },
                {
                    verb: "createSPList",
                    listName: "{parameter:EngineeringRequestsListName}",
                    title: "Engineering Requests",
                    desc: "Sample list created by the provisioning plan",
                    template: 100,
                    enableContentTypes: false,
                    hidden: false,
                    onQuickLaunch: true,
                    enableAttachments: true,
                    enableFolderCreation: true,
                    enableVersioning: true,
                    forceCheckout: false,
                    majorVersionLimit: 50,
                    readSecurity: 1,
                    writeSecurity: 1,
                    noCrawl: false,
                    enableModeration: false,
                    subactions: [
                        {
                            verb: "enableSPListRating",
                            ratingType: "Likes",
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Text",
                            fieldName: "ObsoleteField",
                            displayName: "Obsolete Field",
                            maxLength: 120,
                            required: true,
                            addToDefaultView: true,
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Number",
                            fieldName: "RequestScore",
                            displayName: "Request Score",
                            minimumValue: 0,
                            maximumValue: 100,
                            defaultValue: 0,
                            showAsPercentage: false,
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Calculated",
                            fieldName: "RequestScoreDouble",
                            displayName: "Request Score (2)",
                            formula: '=CONCATENATE([Request Score]," (2)")',
                            outputType: 'Text',
                            addToDefaultView: true,
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Currency",
                            fieldName: "RequestCost",
                            displayName: "Request Cost",
                            minimumValue: 0,
                            maximumValue: 100000,
                            currencyLocaleId: 1033,
                            defaultValue: 0,
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "addSPField",
                            fieldType: "DateTime",
                            fieldName: "RequestedOn",
                            displayName: "Requested On",
                            displayFormat: "DateTime",
                            calendarType: "Gregorian",
                            friendlyDisplayFormat: "Relative",
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Text",
                            fieldName: "RequestTitle",
                            displayName: "Request Title",
                            maxLength: 120,
                            required: true,
                            addToDefaultView: true,
                        },
                        {
                            verb: "addSPField",
                            fieldType: "MultilineText",
                            fieldName: "RequestDetails",
                            displayName: "Request Details",
                            numberOfLines: 6,
                            richText: true,
                            appendOnly: false,
                            allowHyperlink: true,
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Text",
                            fieldName: "RequestTitle",
                            displayName: "Request Title (Updated)",
                            maxLength: 200,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Number",
                            fieldName: "RequestScore",
                            maximumValue: 200,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Calculated",
                            fieldName: "RequestScoreDouble",
                            formula: '=CONCATENATE([Request Score]," (3)")',
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Location",
                            fieldName: "RequestLocation",
                            displayName: "Request Location",
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Location",
                            fieldName: "RequestLocation",
                            description: "Where the request applies",
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Image",
                            fieldName: "RequestImage",
                            displayName: "Request Image",
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Image",
                            fieldName: "RequestImage",
                            description: "An image associated with the request",
                        },
                        {
                            verb: "addSPField",
                            fieldType: "User",
                            fieldName: "RequestOwner",
                            displayName: "Request Owner",
                            selectionMode: "PeopleOnly",
                            allowMultipleValues: false,
                            presence: true,
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "User",
                            fieldName: "RequestOwner",
                            selectionMode: "PeopleAndGroups",
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Lookup",
                            fieldName: "RequestCategory",
                            displayName: "Request Category",
                            lookupListName: "{parameter:RequestCategoriesListName}",
                            showField: "Title",
                            allowMultipleValues: false,
                            relationshipDeleteBehavior: "None",
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Lookup",
                            fieldName: "RequestCategory",
                            description: "Category of the request",
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Currency",
                            fieldName: "RequestCost",
                            maximumValue: 250000,
                            defaultValue: 100,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "DateTime",
                            fieldName: "RequestedOn",
                            friendlyDisplayFormat: "Disabled",
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Boolean",
                            fieldName: "IsUrgent",
                            displayName: "Is Urgent",
                            defaultValue: false,
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Boolean",
                            fieldName: "IsUrgent",
                            defaultValue: true,
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Choice",
                            fieldName: "RequestType",
                            displayName: "Request Type",
                            choices: ["Bug", "Feature", "Question"],
                            editFormat: "RadioButtons",
                            fillInChoice: true,
                            defaultChoice: "Feature",
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Choice",
                            fieldName: "RequestType",
                            editFormat: "Dropdown",
                        },
                        {
                            verb: "addSPField",
                            fieldType: "MultiChoice",
                            fieldName: "RequestAreas",
                            displayName: "Request Areas",
                            choices: ["UX", "API", "Data", "Infra"],
                            fillInChoice: false,
                            defaultValue: ["API"],
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "MultiChoice",
                            fieldName: "RequestAreas",
                            defaultValue: ["UX", "API"],
                        },
                        {
                            verb: "addSPField",
                            fieldType: "Url",
                            fieldName: "ReferenceLink",
                            displayName: "Reference Link",
                            displayFormat: "Hyperlink",
                            required: false,
                            addToDefaultView: true,
                        },
                        {
                            verb: "modifySPField",
                            fieldType: "Url",
                            fieldName: "ReferenceLink",
                            displayFormat: "Image",
                        },
                        // {
                        //     verb: "deleteSPField",
                        //     fieldName: "ObsoleteField",
                        // },
                    ],
                },
                {
                    verb: "modifySPList",
                    listName: "{parameter:EngineeringRequestsListName}",
                    title: "Engineering Requests (Updated)",
                    description: "Updated by modifySPList action",
                    enableVersioning: true,
                    majorVersionLimit: 25,
                    onQuickLaunch: true,
                    subactions: [
                        {
                            verb: "enableSPListRating",
                            ratingType: "Stars",
                        },
                    ],
                },
                {
                    verb: "createSPList",
                    listName: "{parameter:EngineeringDocumentsListName}",
                    title: "Engineering Documents",
                    desc: "Sample document library created by the provisioning plan",
                    // 101 = Document Library
                    template: 101,
                    enableContentTypes: true,
                    hidden: false,
                    onQuickLaunch: true,
                    enableFolderCreation: true,
                    // Versioning settings typically used for document libraries
                    enableVersioning: true,
                    enableMinorVersions: true,
                    majorVersionLimit: 50,
                    majorWithMinorVersionsLimit: 25,
                    // 0=Reader, 1=Author, 2=Approver
                    draftVersionVisibility: 1,
                    // Optional: common doclib settings
                    forceCheckout: false,
                    noCrawl: false,
                    enableModeration: false,
                },
                {
                    verb: "createSPList",
                    listName: "tempToRecycle",
                    title: "Temp (Recycle Demo)",
                    desc: "Temporary list created only to demonstrate deleteSPList with recycle",
                    template: 100,
                    enableVersioning: false,
                },
                // {
                //     verb: "deleteSPList",
                //     listName: "tempToRecycle",
                //     recycle: true,
                // },
                // {
                //     verb: "deleteSPField",
                //     fieldName: "TemporarySiteField",
                // },
            ],
        },
    ],
};

export default examplePlan;
